# entry-playbook
---
  - hosts: ceph_nodes
    roles:
      - centos7-ceph

    tasks:
      - debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

  - hosts: ceph_primary_node
    roles:
      - {role: centos7-ceph-deploy }

    tasks:
      - debug: msg="ceph_primary_node OK"
