---
- hosts: spring-boot-microservices
  tasks:
    - debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

  roles:
    - jdk8
    - { role: ragna-packages, package_repo: "http://rawgit.com/ragnarokkrr/rgn_vm_containers/master/vagrant_springboot_ha/provisioning", package_name: "ragna-goodbye_0.1.0-1_all.deb", conf_file: "/opt/local/ragna-goodbye/conf/ragna-goodbye.properties", service_name: "ragna-goodbye"  }
