apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask
    name: flask
    tier: frontend
  name: flask-app
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: flask
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}