apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  clusterIP: None
  ports:
    - name: headless
      port: 6379
      targetPort: 0
  selector:
    service.name: redis
status:
  loadBalancer: {}