# centos7-ceph-deploy/tasks/main.yml
---

  - name: get host names for cephnodes groups
    set_fact:
      ceph_nodes_list="{{ groups['ceph_nodes'] | join(' ') }}"
      ceph_primary_node="{{ groups['ceph_primary_node'] | join('') }}"

  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
    when: hostvars[item].ansible_default_ipv4.address is defined
    with_items: "groups['all']"

  - include: primary_node.yml
    when: inventory_hostname == {{ ceph_primary_node }}
