- hosts: all
  tasks:

    - block:

      - name: nginx> install
        apt: name=nginx update_cache=yes

      - name: nginx> enable configuration
        file: >
          dest=/etc/nginx/sites-enabled/default
          src=/etc/nginx/sites-available/default
          state=link

      - name: nginx> copy index.html
        template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

      - name: nginx> restart
        service: name=nginx state=restarted

    - block:
      - name: couchdb> repo install
        apt: name=software-properties-common state=present force=yes

      - name: couchdb> ppa
        apt_repository: repo='ppa:couchdb/stable'

      - name: couchdb> install
        apt: name=couchdb update_cache=yes  state=present force=yes

    - block:
      - name: mongodb> install
        apt_key: keyserver=keyserver.ubuntu.com id=EA312927


    - block:
      - name: git> install
        apt: name=git update_cache=yes state=present

    - block:

      - name: lynx> install
        apt: name=lynx-cur state=present

    - block:
      - name: nodejs4> repo install
        apt_repository: repo='{{ item }} https://deb.nodesource.com/node_4.x {{ ansible_distribution_release|lower }} main' state=present
        with_items:
          - deb-src
          - deb

      - name: nodejs4> install
        apt: name=nodejs update_cache=yes state=present force=yes

      - name: nodejs4> Install node-gyp
        command: "npm install -g node-gyp"

      - name: nodejs4> Install deploy tools
        command: "npm install -g {{ item }}"
        with_items:
          - bower
          - grunt-cli
          - browserify
          - yo

      - name: nodejs4> Install test libs
        command: "npm install -g {{ item }}"
        with_items:
          - jasmine
          - mocha
          - chai
