---
- block:

  - debug: msg="Provisioning JAVA"


  - name: download Java RPM
    shell:
      "curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o /home/vagrant/{{ jre }} {{ jre_path }}"
    args:
      creates: "/home/vagrant/{{ jre }}"
    sudo: yes

  - name: msg="fix update-alternatives symlink"
    file: >
      src=/usr/sbin/update-alternatives
      dest=/usr/sbin/alternatives
      state=link

  - name: msg="Install RPM /tmp/{{ jre }}"
    shell: "zypper --non-interactive --no-gpg-checks --quiet install /home/vagrant/{{ jre }} "
    args:
      executable: /bin/bash
