---
  - name: add EPEL repository
    yum: name=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

  #- name: Add GLUSTERFS repository
  #  yum_repository:
  #    name: glusterfs-epel
  #    description: GLUSTERFS EPEL YUM repo
  #    baseurl: http://download.gluster.org/pub/gluster/glusterfs/LATEST/CentOS/glusterfs-epel.repo

  - name: Fetch glusterfs repo file
    get_url: >
      dest=/etc/yum.repos.d/glusterfs-epel.repo
      url=http://download.gluster.org/pub/gluster/glusterfs/LATEST/CentOS/glusterfs-epel.repo

  - name: Set repo file permissions
    file: >
      owner=root group=root mode=0644
      path=/etc/yum.repos.d/glusterfs-epel.repo

  - name: install glusterfs server
    yum: name={{ item }} state=present
    with_items:
      - glusterfs-server
      - glusterfs-client
      - attr
